import os


def write_custom_extension_file():
	file_path  = os.path.join(os.path.dirname(os.path.realpath(__file__)),'..','src','custom_extensions.cpp')
	header = '''
#include "custom_extensions/custom_extensions.hpp"

//! This class is auto-generated by scripts/geenrate_extension_initializer.py
//! It depends on substrait/extensions yaml files
namespace duckdb{

void SubstraitCustomFunctions::Initialize(){
  InsertCustomFunction("name", {"types"}, {"path"});
	'''
	footer = '''}

}'''
	# Open the file in write mode
	with open(file_path, 'w') as file:
	# Write new content to the file
		file.write(header)
		file.write("ayo")
		file.write(footer)
