#include "custom_extensions/custom_extensions.hpp"

//! This class is auto-generated by scripts/geenrate_extension_initializer.py
//! It depends on substrait/extensions yaml files
namespace duckdb{

void SubstraitCustomFunctions::Initialize(){
  InsertCustomFunction("name", {"types"}, {"path"});
}

}
