on: [push, pull_request,repository_dispatch]

defaults:
  run:
    shell: bash

jobs:
  python:
    name: Python
    runs-on: macos-latest
    env:
      GEN: ninja

    steps:
    - name: Install Ninja
      run: brew install ninja

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Update DuckDB submodule
      run: |
        git config --global --add safe.directory '*'
        make pull

    - name: Build DuckDB (Python)
      run: |
        cd duckdb/tools/pythonpkg
        python3 -m pip install .

    - name: Build Substrait
      run: make release

    - name: Install Python Dependencies
      shell: bash
      run: |
        pip install -r test/python/requirements-dev.txt
        pip uninstall protobuf -y
        pip install --no-binary protobuf protobuf

    - name: Test Python
      run: |
        (cd test/python && python -m pytest)